FROM 200ms/devuan_dev2:latest

ENV DUNAME='proj'
ENV DEVUID=1000
ENV DEVGID=1000

ENV RUNAME='test'
ENV RUNUID=3300
ENV RUNGID=3300

ENV PCKGS_BASE=''
ENV PCKGS_DEV='make gcc libc-dev libfuse-dev'

RUN dev2_addtools.sh $PCKGS_BASE $PCKGS_DEV


RUN addgroup --gid $DEVGID $DUNAME && \
    USERHIDPASS=$(dd if=/dev/urandom status=none bs=1024 count=1 | md5sum | cut -c -16) && \
    printf "$USERHIDPASS\n$USERHIDPASS\n$DUNAME\n\n\n\n\nY" | adduser --uid $DEVUID --gid $DEVGID $DUNAME

RUN addgroup --gid $RUNGID $RUNAME && \
    USERHIDPASS=$(dd if=/dev/urandom status=none bs=1024 count=1 | md5sum | cut -c -16) && \
    printf "$USERHIDPASS\n$USERHIDPASS\n$RUNAME\n\n\n\n\nY" | adduser --uid $RUNUID --gid $RUNGID $RUNAME

USER $DUNAME
WORKDIR /home/$DUNAME


ENTRYPOINT ["bash"]
