version: '3.9'

services:
  # musl libc
  musl:
    build:
      context: .
      dockerfile: Dockerfile-alp
    cap_add: ['SYS_ADMIN']
    devices:
      - /dev/fuse
    hostname: MUSL
    container_name: musl
    volumes: 
      - ../src:/home/proj/src
      - ../tests:/home/proj/tests
      - ../Makefile:/home/proj/Makefile
      - ./data:/d2str
    entrypoint: ["/usr/bin/tail", "-f", "/dev/stderr"]

  # GNU libc
  gnu:
    build:
      context: .
      dockerfile: Dockerfile-deb
    cap_add: ['SYS_ADMIN']
    devices:
      - /dev/fuse
    hostname: GNU
    container_name: gnu
    volumes:
      - ../src:/home/proj/src
      - ../tests:/home/proj/tests
      - ../Makefile:/home/proj/Makefile
      - ./data:/d2str
    entrypoint: [ "/usr/bin/tail", "-f", "/dev/stderr" ]
