
# variables declarations
OUTPUT := teafs
OUTPUT_LIB := libTeafs.so

CC := gcc
LIBS := -lfuse -L. -lTeafs
CFLAGS := -D_FILE_OFFSET_BITS=64

SOURCES_LIB := ${wildcard lib/*.c}
OBJS_LIB := ${patsubst %.c, %.o, ${SOURCES_S1}}

SOURCES := ${wildcard *.c format/*.c shell/*.c core/*.c}
OBJS := ${patsubst %.c, %.o, ${SOURCES}}

# setting additional options

CFLAGS += -Wall
#CFLAGS += -Wimplicit-function-declaration

ifeq ("${DEBUG}","y")
	CFLAGS += -g1
else ifeq ("${DEBUG}","Y")
	CFLAGS += -g3
endif

# targets definitions

.PHONY : one-command-compile \
         clean deepclean

#all: ${OUTPUT}

${OUTPUT} : ${OBJS}
	${CC} ${OBJS} ${LIBS} -o ${OUTPUT}

one-command-compile:
	${CC} ${SOURCES_LIB} -shared -fPIC ${CFLAGS} -o ${OUTPUT_LIB}
	${CC} ${LIBS} ${SOURCES} ${CFLAGS} -o ${OUTPUT}

clean:
	rm -f ${OBJS}
	rm -f ${OUTPUT}

	rm -f ${OUTPUT_LIB}

deepclean: clean
	find . -type f -name "*~" -exec rm '{}' \;
	find . -type f -name "*.bak" -exec rm '{}' \;

depend:
	makedepend -Y. *.c core/*.c shell/*.c lib/*.c
# DO NOT DELETE
